name: regenerate-openapi

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - run: composer install --no-interaction --prefer-dist
      - run: composer generate
      - run: find src tests -name '*.php' -print0 | xargs -0 -n 1 php -l
      - run: composer analyse
      - run: composer test
